/** @internal */
type CreateGitIgnoreInjects = {
   writeFile?: (path: string, text: string) => Promise<void>
}
/** Options for createGitignore */
export type CreateGitIgnoreOptions = {
   /** If true, the .gitignore file will not be written. */
   dryRun?: boolean
}
/** Creates a .gitignore file in the current directory */
export async function createGitIgnore(
   { dryRun = false }: CreateGitIgnoreOptions = {},
   { writeFile = Deno.writeTextFile }: CreateGitIgnoreInjects = {},
): Promise<string | void> {
   if (dryRun) {
      return Promise.resolve(TEMPLATE)
   }

   await writeFile('.gitignore', TEMPLATE)
}

const TEMPLATE = `
##########################
### IDE specific files ###
##########################

# Ignore files generated by JetBrains IDEs
.idea
# Ignore files generated by VSCode
.vscode

###########################
### Deno specific files ###
###########################

# Ignore deno cache
vendor
# Ignore deno coverage files
coverage
`
